export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const DELETE_PRODUCT_FROM_CART = 'DELETE_PRODUCT_FROM_CART';
export const DATA_PRODUCTS_LOADED = 'DATA_PRODUCTS_LOADED';
export const DATA_PRODUCTS_REQUESTED = 'DATA_PRODUCTS_REQUESTED';
export const DATA_PRODUCT_ERROR = 'DATA_PRODUCTS_API_FAILED';
export const VOUCHER_APPLIED = 'VOUCHER_APPLIED';
